"""Simple i10n/i18n runtime translations for the UI."""

from __future__ import annotations


SUPPORTED_LANGUAGES = {
    "es": "Español",
    "en": "English",
    "pt": "Português",
}


TRANSLATIONS = {
    "es": {
        "app_title": "Normalizador Audio",
        "header_subtitle": "Normalización LUFS profesional con FFmpeg",
        "menu_file": "Archivo",
        "menu_tools": "Herramientas",
        "menu_help": "Ayuda",
        "menu_language": "Idioma",
        "action_update_deps": "Actualizar dependencias",
        "action_check_deps": "Verificar dependencias",
        "action_clean_cache": "Limpiar caché",
        "action_restore": "Restaurar configuración",
        "action_exit": "Salir",
        "action_logs": "Ver logs",
        "action_errors": "Reporte de errores",
        "action_settings": "Configuración...",
        "action_theme": "Cambiar tema",
        "action_manual": "Manual",
        "action_support_project": "Ayuda al proyecto",
        "action_ffmpeg": "Descargar FFmpeg",
        "action_updates": "Verificar actualizaciones",
        "action_about": "Acerca de",
        "tab_normalize": "Normalizar",
        "tab_profile": "Perfil",
        "tab_report": "Reporte",
        "btn_input": "Origen",
        "btn_output": "Destino",
        "btn_clear_output": "Limpiar destino",
        "btn_clear_list": "Limpiar lista",
        "label_input_empty": "Origen: -",
        "label_output_empty": "Destino: -",
        "label_input_value": "Origen: {name}",
        "label_output_value": "Destino: {name}",
        "label_videos": "Videos",
        "label_videos_hint": "Arrastra · doble clic o Espacio para seleccionar",
        "table_selected": "Selección",
        "table_file": "Archivo",
        "table_size": "Tamaño",
        "table_status": "Estado",
        "btn_select_all": "Todo",
        "btn_select_none": "Nada",
        "label_progress": "Progreso",
        "btn_start": "Iniciar",
        "btn_cancel": "Cancelar",
        "status_ready": "Listo",
        "status_canceling": "Cancelando...",
        "profile_title": "Perfil de audio",
        "profile_subtitle": "Elige un video de referencia, extrae su perfil y aplícalo al procesamiento general",
        "profile_no_file": "Sin archivo",
        "btn_pick_video": "Elegir...",
        "btn_analyze": "Extraer perfil",
        "btn_clear_profile": "Borrar perfil",
        "group_output": "Salida",
        "waveform_group": "Waveform",
        "waveform_empty": "Selecciona un video para ver la forma de onda.",
        "waveform_loading": "Generando waveform...",
        "waveform_unavailable": "No se pudo generar la previsualizacion.",
        "btn_apply_profile": "Aplicar al procesamiento general",
        "report_title": "Antes / después",
        "report_file": "Archivo",
        "report_before_i": "Antes (I)",
        "report_before_lra": "Antes (LRA)",
        "report_before_tp": "Antes (TP)",
        "report_after_i": "Después (I)",
        "report_after_lra": "Después (LRA)",
        "report_after_tp": "Después (TP)",
        "btn_export_csv": "CSV",
        "btn_export_txt": "TXT",
        "btn_clear_report": "Limpiar",
        "report_filename_base": "reporte",
        "group_summary": "Resumen",
        "summary_no_data": "Sin datos",
        "summary_text": "Total {total} · ok {ok} · error {fail} · {ratio:.0f}%\nLUFS medio: {avg_before:.2f} -> {avg_after:.2f} (D {delta:+.2f})",
        "msg_attention": "Atención",
        "msg_success": "Éxito",
        "msg_error": "Error",
        "msg_info": "Info",
        "msg_confirm": "Confirmar",
        "dialog_close": "Cerrar",
        "settings_title": "Configuración",
        "settings_input": "Origen:",
        "settings_output": "Destino:",
        "settings_browse": "Explorar...",
        "settings_save": "Guardar",
        "settings_cancel": "Cancelar",
        "pick_input_folder": "Seleccionar carpeta de origen",
        "pick_output_folder": "Seleccionar carpeta de destino",
        "pick_reference_video": "Seleccionar video de referencia",
        "video_filter": "Videos (*.mp4 *.mkv *.mov *.avi *.flv *.webm);;Todos (*.*)",
        "all_filter": "Todos (*.*)",
        "save_csv": "Guardar CSV",
        "save_txt": "Guardar TXT",
        "csv_filter": "CSV (*.csv);;Todos (*.*)",
        "txt_filter": "Texto (*.txt);;Todos (*.*)",
        "manual_title": "Manual",
        "manual_text": "Guía rápida:\n1. Selecciona origen y destino.\n2. Marca videos.\n3. Ajusta LUFS/LRA/TP.\n4. Inicia y revisa Reporte.",
        "about_title": "Acerca de",
        "about_text": "FFmpeg Master Vol Normalizer v{version}\n\nNormalizador de volumen para video/audio con ffmpeg loudnorm.\nInterfaz: PyQt6\nLicencia: MIT",
        "support_title": "Ayuda al proyecto",
        "support_heading": "💙 Apoya el proyecto",
        "support_message": "Si esta herramienta te ha resultado útil y te ha ayudado en tu trabajo, puedes apoyar su desarrollo y mantenimiento con una contribución voluntaria.",
        "support_note": "✨ Tu apoyo ayuda a mantener mejoras, correcciones y nuevas funciones.",
        "support_target": "🔗 Enlace de pago (Wise): {target}",
        "support_scan_hint": "📱 Escanea el código QR o usa el botón de acción.",
        "support_open": "Abrir enlace de pago",
        "support_copy": "Copiar enlace",
        "support_link_copied": "Enlace de pago copiado al portapapeles.",
        "support_qr_error": "No se pudo generar el código QR en este momento.",
        "deps_missing_title": "Dependencias faltantes",
        "deps_missing_text": "Faltan dependencias necesarias:\n\n{missing}\n\n¿Abrir el sitio de descarga de FFmpeg?",
        "cannot_start_without_ffmpeg": "No se puede iniciar sin FFmpeg instalado.",
        "exit_title": "Salir",
        "exit_text": "¿Deseas salir?",
        "busy_title": "Advertencia",
        "busy_text": "La aplicación está procesando. Cancela o espera a que termine.",
        "language_spanish": "Español",
        "language_english": "English",
        "language_portuguese": "Portugués",
        "logs_title": "Registros",
        "logs_empty": "No hay registros aún.",
        "error_reading_logs": "Error leyendo logs: {error}",
        "errors_report_title": "Reporte de Errores",
        "errors_report_ok": "No se encontraron errores.",
        "errors_report_header": "REPORTE DE ERRORES\n{line}\nTotal: {count}\n\n{items}",
        "update_deps_question": "¿Actualizar PyQt6 vía pip?",
        "update_deps_ok": "Dependencias actualizadas. Reinicia la aplicación.",
        "update_deps_fail": "No se pudieron actualizar dependencias.\n\n{error}",
        "deps_title": "Dependencias",
        "deps_all_ok": "{info}\n\nTodo correcto.",
        "deps_missing": "{info}\n\nFaltan dependencias.",
        "clean_cache_question": "¿Eliminar archivos temporales?",
        "clean_cache_result": "{count} archivos eliminados.",
        "restore_config_question": "¿Restaurar configuración por defecto?",
        "restore_config_done": "Configuración restaurada. Reinicia la aplicación.",
        "settings_saved": "Configuración guardada.",
        "download_ffmpeg_title": "Descargar FFmpeg",
        "download_ffmpeg_question": "¿Abrir sitio de descarga de FFmpeg?",
        "version_title": "Versión",
        "version_text": "Versión actual: {version}\nVerificado: {checked}\n\nEstás usando la última versión disponible.",
        "update_available_title": "Actualización disponible",
        "update_available_message": "Versión {latest} disponible (tienes {current})\n\n¿Descargarla?",
        "update_check_error": "No se pudo verificar actualizaciones. Intenta más tarde.",
        "update_up_to_date": "Ya tienes la última versión ({version}).",
        "btn_download": "Descargar",
        "btn_ignore": "Ignorar",
        "preset_label": "Preset:",
        "preset_custom": "Custom",
        "preset_applied": "Preset {name} aplicado ({lufs} LUFS · LRA {lra} · TP {tp} dB)",
        "gpu_label": "GPU accel:",
        "gpu_detected": "{method} detectado",
        "gpu_none": "No disponible",
        "gpu_enabled_hint": "Acelera la lectura de video con hardware",
        "parallel_label": "Paralelo:",
        "parallel_hint": "{workers} procesos simultáneos",
        "processing_parallel": "Procesando en paralelo ({workers}): {done}/{total}",
        "item_pending": "Pendiente",
        "processing_item": "Procesando {index}/{total}: {name}...",
        "status_analyzing": "Analizando...",
        "status_normalizing": "Normalizando...",
        "status_completed": "Completado",
        "status_timeout": "Timeout",
        "status_canceled": "Cancelado",
        "status_error": "Error",
        "status_success": "Éxito",
        "status_finished": "Finalizado",
        "finished_counts": "Procesados: {ok}\nErrores: {fail}",
        "profile_analyzing": "Analizando...",
        "analyzer_saved": "Video analizado. Perfil guardado.",
        "analysis_error_title": "Error de análisis",
        "no_videos_selected": "Debes seleccionar al menos un video para normalizar.",
        "profile_applied": "Perfil de audio aplicado correctamente.\n\nLUFS: {lufs} · LRA: {lra} · TP: {tp} dB",
        "profile_info_loaded": "VIDEO ANALIZADO\n{line}\nArchivo: {filename}\nFecha: {date}\n\nPARÁMETROS DETECTADOS\n{line}\nInput Loudness (I): {input_i:.2f} LUFS\nLoudness Range (LRA): {input_lra:.2f} LU\nTrue Peak (TP): {input_tp:.2f} dB\nThreshold: {input_thresh:.2f} dB\nTarget Offset: {target_offset:.2f}\n\nListo para usar como referencia",
        "profile_info_empty": "SIN PERFIL CARGADO\n\n1. Selecciona un video de referencia\n2. Haz clic en Extraer perfil\n3. Espera el resultado\n4. Aplica el perfil al procesamiento general",
        "manual_text_full": "NORMALIZADOR AUDIO · MANUAL PROFESIONAL\n============================================================\n\n1) Qué hace esta aplicación\nNormaliza el volumen de lotes de videos para que suenen consistentes,\nusando FFmpeg y el filtro loudnorm basado en LUFS.\n\n2) Flujo recomendado\n1. En la pestaña Normalizar, elige carpeta de origen.\n2. Marca los videos a procesar.\n3. Selecciona carpeta de destino.\n4. Ajusta LUFS / LRA / TP.\n5. Inicia el proceso y espera.\n6. Revisa la pestaña Reporte y exporta CSV/TXT.\n\n3) Parámetros\n- LUFS: loudness percibido (común en web: -14).\n- LRA: rango dinámico (bajo = uniforme, alto = más natural).\n- TP: pico máximo para evitar clipping (recomendado: -1.5 dB).\n\n4) Perfil de referencia\n1. Abre pestaña Perfil.\n2. Elige video de referencia.\n3. Extrae perfil.\n4. Aplica al procesamiento general.\n5. Vuelve a Normalizar y procesa.\n\n5) Reporte\nMuestra antes/después por video (I, LRA, TP), estado por archivo\ny resumen global con promedio LUFS y porcentaje de éxito.\n\n6) Utilidades\n- Configuración de rutas por defecto.\n- Cambio de tema claro/oscuro.\n- Visualización de logs y reporte de errores.\n- Limpieza de caché temporal.\n\n7) Problemas comunes\n- FFmpeg no encontrado: instalar y agregar a PATH.\n- No aparecen videos: revisar formatos compatibles.\n- Error al exportar: revisar permisos de escritura.\n- Timeout: procesar en lotes más pequeños.\n\n8) Buenas prácticas\n- Usa destino distinto al origen.\n- Prueba con 1-2 videos antes del lote completo.\n- Para web, inicia con -14 LUFS, LRA moderado y TP -1.5 dB.\n\n9) Resultado esperado\nVolumen final más consistente, profesional y cómodo para escucha continua.",
    },
    "en": {
        "app_title": "Audio Normalizer",
        "header_subtitle": "Professional LUFS normalization with FFmpeg",
        "menu_file": "File",
        "menu_tools": "Tools",
        "menu_help": "Help",
        "menu_language": "Language",
        "action_update_deps": "Update dependencies",
        "action_check_deps": "Check dependencies",
        "action_clean_cache": "Clean cache",
        "action_restore": "Restore settings",
        "action_exit": "Exit",
        "action_logs": "View logs",
        "action_errors": "Error report",
        "action_settings": "Settings...",
        "action_theme": "Toggle theme",
        "action_manual": "Manual",
        "action_support_project": "Support the project",
        "action_ffmpeg": "Download FFmpeg",
        "action_updates": "Check updates",
        "action_about": "About",
        "tab_normalize": "Normalize",
        "tab_profile": "Profile",
        "tab_report": "Report",
        "btn_input": "Input",
        "btn_output": "Output",
        "btn_clear_output": "Clear output",
        "btn_clear_list": "Clear list",
        "label_input_empty": "Input: -",
        "label_output_empty": "Output: -",
        "label_input_value": "Input: {name}",
        "label_output_value": "Output: {name}",
        "label_videos": "Videos",
        "label_videos_hint": "Drag · double click or Space to select",
        "table_selected": "Select",
        "table_file": "File",
        "table_size": "Size",
        "table_status": "Status",
        "btn_select_all": "All",
        "btn_select_none": "None",
        "label_progress": "Progress",
        "btn_start": "Start",
        "btn_cancel": "Cancel",
        "status_ready": "Ready",
        "status_canceling": "Canceling...",
        "profile_title": "Audio profile",
        "profile_subtitle": "Choose a reference video, extract its profile and apply it to general processing",
        "profile_no_file": "No file",
        "btn_pick_video": "Choose...",
        "btn_analyze": "Extract profile",
        "btn_clear_profile": "Clear profile",
        "group_output": "Output",
        "waveform_group": "Waveform",
        "waveform_empty": "Select a video to preview its waveform.",
        "waveform_loading": "Generating waveform...",
        "waveform_unavailable": "Could not generate waveform preview.",
        "btn_apply_profile": "Apply to general processing",
        "report_title": "Before / after",
        "report_file": "File",
        "report_before_i": "Before (I)",
        "report_before_lra": "Before (LRA)",
        "report_before_tp": "Before (TP)",
        "report_after_i": "After (I)",
        "report_after_lra": "After (LRA)",
        "report_after_tp": "After (TP)",
        "btn_export_csv": "CSV",
        "btn_export_txt": "TXT",
        "btn_clear_report": "Clear",
        "report_filename_base": "report",
        "group_summary": "Summary",
        "summary_no_data": "No data",
        "summary_text": "Total {total} · ok {ok} · fail {fail} · {ratio:.0f}%\nAvg LUFS: {avg_before:.2f} -> {avg_after:.2f} (D {delta:+.2f})",
        "msg_attention": "Attention",
        "msg_success": "Success",
        "msg_error": "Error",
        "msg_info": "Info",
        "msg_confirm": "Confirm",
        "dialog_close": "Close",
        "settings_title": "Settings",
        "settings_input": "Input:",
        "settings_output": "Output:",
        "settings_browse": "Browse...",
        "settings_save": "Save",
        "settings_cancel": "Cancel",
        "pick_input_folder": "Select input folder",
        "pick_output_folder": "Select output folder",
        "pick_reference_video": "Select reference video",
        "video_filter": "Videos (*.mp4 *.mkv *.mov *.avi *.flv *.webm);;All (*.*)",
        "all_filter": "All (*.*)",
        "save_csv": "Save CSV",
        "save_txt": "Save TXT",
        "csv_filter": "CSV (*.csv);;All (*.*)",
        "txt_filter": "Text (*.txt);;All (*.*)",
        "manual_title": "Manual",
        "manual_text": "Quick guide:\n1. Select input and output.\n2. Pick videos.\n3. Set LUFS/LRA/TP.\n4. Start and check Report.",
        "about_title": "About",
        "about_text": "FFmpeg Master Vol Normalizer v{version}\n\nVolume normalizer for video/audio with ffmpeg loudnorm.\nUI: PyQt6\nLicense: MIT",
        "support_title": "Support the project",
        "support_heading": "💙 Support the project",
        "support_message": "If this tool has been useful and has helped your workflow, consider making a voluntary contribution to support ongoing development and maintenance.",
        "support_note": "✨ Your support helps fund improvements, fixes, and new features.",
        "support_target": "🔗 Payment link (Wise): {target}",
        "support_scan_hint": "📱 Scan the QR code or use the action button.",
        "support_open": "Open payment link",
        "support_copy": "Copy link",
        "support_link_copied": "Payment link copied to the clipboard.",
        "support_qr_error": "The QR code could not be generated right now.",
        "deps_missing_title": "Missing dependencies",
        "deps_missing_text": "Required dependencies are missing:\n\n{missing}\n\nOpen FFmpeg download page?",
        "cannot_start_without_ffmpeg": "Cannot start without FFmpeg installed.",
        "exit_title": "Exit",
        "exit_text": "Do you want to exit?",
        "busy_title": "Warning",
        "busy_text": "The app is processing. Cancel or wait for completion.",
        "language_spanish": "Spanish",
        "language_english": "English",
        "language_portuguese": "Portuguese",
        "logs_title": "Logs",
        "logs_empty": "No logs yet.",
        "error_reading_logs": "Error reading logs: {error}",
        "errors_report_title": "Error Report",
        "errors_report_ok": "No errors found.",
        "errors_report_header": "ERROR REPORT\n{line}\nTotal: {count}\n\n{items}",
        "update_deps_question": "Update PyQt6 using pip?",
        "update_deps_ok": "Dependencies updated. Restart the app.",
        "update_deps_fail": "Dependencies could not be updated.\n\n{error}",
        "deps_title": "Dependencies",
        "deps_all_ok": "{info}\n\nAll good.",
        "deps_missing": "{info}\n\nMissing dependencies.",
        "clean_cache_question": "Delete temporary files?",
        "clean_cache_result": "{count} files deleted.",
        "restore_config_question": "Restore default settings?",
        "restore_config_done": "Settings restored. Restart the app.",
        "settings_saved": "Settings saved.",
        "download_ffmpeg_title": "Download FFmpeg",
        "download_ffmpeg_question": "Open FFmpeg download website?",
        "version_title": "Version",
        "version_text": "Current version: {version}\nChecked: {checked}\n\nYou are using the latest available version.",        "update_available_title": "Update available",
        "update_available_message": "Version {latest} available (you have {current})\n\nDownload it?",
        "update_check_error": "Could not check for updates. Try again later.",
        "update_up_to_date": "You already have the latest version ({version}).",
        "btn_download": "Download",
        "btn_ignore": "Ignore",
        "preset_label": "Preset:",
        "preset_custom": "Custom",
        "preset_applied": "Preset {name} applied ({lufs} LUFS · LRA {lra} · TP {tp} dB)",
        "gpu_label": "GPU accel:",
        "gpu_detected": "{method} detected",
        "gpu_none": "Not available",
        "gpu_enabled_hint": "Accelerates video reading with hardware",
        "parallel_label": "Parallel:",
        "parallel_hint": "{workers} simultaneous jobs",
        "processing_parallel": "Parallel processing ({workers}): {done}/{total}",
        "item_pending": "Pending",
        "processing_item": "Processing {index}/{total}: {name}...",
        "status_analyzing": "Analyzing...",
        "status_normalizing": "Normalizing...",
        "status_completed": "Completed",
        "status_timeout": "Timeout",
        "status_canceled": "Canceled",
        "status_error": "Error",
        "status_success": "Success",
        "status_finished": "Finished",
        "finished_counts": "Processed: {ok}\nErrors: {fail}",
        "profile_analyzing": "Analyzing...",
        "analyzer_saved": "Video analyzed. Profile saved.",
        "analysis_error_title": "Analysis error",
        "no_videos_selected": "You must select at least one video to normalize.",
        "profile_applied": "Audio profile applied successfully.\n\nLUFS: {lufs} · LRA: {lra} · TP: {tp} dB",
        "profile_info_loaded": "ANALYZED VIDEO\n{line}\nFile: {filename}\nDate: {date}\n\nDETECTED PARAMETERS\n{line}\nInput Loudness (I): {input_i:.2f} LUFS\nLoudness Range (LRA): {input_lra:.2f} LU\nTrue Peak (TP): {input_tp:.2f} dB\nThreshold: {input_thresh:.2f} dB\nTarget Offset: {target_offset:.2f}\n\nReady to use as reference",
        "profile_info_empty": "NO PROFILE LOADED\n\n1. Select a video\n2. Click Extract profile\n3. Wait for the result\n4. Apply profile to general processing",
        "manual_text_full": "AUDIO NORMALIZER · PROFESSIONAL MANUAL\n============================================================\n\n1) What this app does\nIt normalizes volume across video batches so everything sounds consistent,\nusing FFmpeg and LUFS-based loudnorm processing.\n\n2) Recommended workflow\n1. In Normalize tab, choose input folder.\n2. Mark videos to process.\n3. Choose output folder.\n4. Adjust LUFS / LRA / TP.\n5. Start processing and wait.\n6. Review Report tab and export CSV/TXT if needed.\n\n3) Parameters\n- LUFS: perceived loudness (common web target: -14).\n- LRA: dynamic range (lower = more uniform, higher = more natural).\n- TP: max true peak to avoid clipping (recommended: -1.5 dB).\n\n4) Reference profile\n1. Open Profile tab.\n2. Choose reference video.\n3. Extract profile.\n4. Apply to general processing.\n5. Return to Normalize and process batch.\n\n5) Report\nShows before/after values per video (I, LRA, TP), per-file status,\nand a global summary with average LUFS and success ratio.\n\n6) Utilities\n- Default input/output paths configuration.\n- Light/dark theme switch.\n- Logs and error report views.\n- Temporary cache cleanup.\n\n7) Common issues\n- FFmpeg not found: install and add to PATH.\n- No videos listed: verify supported formats.\n- Export error: check write permissions.\n- Timeout: process smaller batches.\n\n8) Good practices\n- Use a different output folder from input.\n- Test with 1-2 videos before full batch.\n- For web, start with -14 LUFS, moderate LRA and TP -1.5 dB.\n\n9) Expected result\nConsistent, professional and comfortable playback volume.",
    },
    "pt": {
        "app_title": "Normalizador de Áudio",
        "header_subtitle": "Normalização LUFS profissional com FFmpeg",
        "menu_file": "Arquivo",
        "menu_tools": "Ferramentas",
        "menu_help": "Ajuda",
        "menu_language": "Idioma",
        "action_update_deps": "Atualizar dependências",
        "action_check_deps": "Verificar dependências",
        "action_clean_cache": "Limpar cache",
        "action_restore": "Restaurar configuração",
        "action_exit": "Sair",
        "action_logs": "Ver logs",
        "action_errors": "Relatório de erros",
        "action_settings": "Configuração...",
        "action_theme": "Alternar tema",
        "action_manual": "Manual",
        "action_support_project": "Apoiar o projeto",
        "action_ffmpeg": "Baixar FFmpeg",
        "action_updates": "Verificar atualizações",
        "action_about": "Sobre",
        "tab_normalize": "Normalizar",
        "tab_profile": "Perfil",
        "tab_report": "Relatório",
        "btn_input": "Origem",
        "btn_output": "Destino",
        "btn_clear_output": "Limpar destino",
        "btn_clear_list": "Limpar lista",
        "label_input_empty": "Origem: -",
        "label_output_empty": "Destino: -",
        "label_input_value": "Origem: {name}",
        "label_output_value": "Destino: {name}",
        "label_videos": "Vídeos",
        "label_videos_hint": "Arraste · duplo clique ou Espaço para selecionar",
        "table_selected": "Seleção",
        "table_file": "Arquivo",
        "table_size": "Tamanho",
        "table_status": "Status",
        "btn_select_all": "Tudo",
        "btn_select_none": "Nada",
        "label_progress": "Progresso",
        "btn_start": "Iniciar",
        "btn_cancel": "Cancelar",
        "status_ready": "Pronto",
        "status_canceling": "Cancelando...",
        "profile_title": "Perfil de áudio",
        "profile_subtitle": "Escolha um vídeo de referência, extraia o perfil e aplique no processamento geral",
        "profile_no_file": "Sem arquivo",
        "btn_pick_video": "Escolher...",
        "btn_analyze": "Extrair perfil",
        "btn_clear_profile": "Apagar perfil",
        "group_output": "Saída",
        "waveform_group": "Waveform",
        "waveform_empty": "Selecione um video para ver a forma de onda.",
        "waveform_loading": "Gerando waveform...",
        "waveform_unavailable": "Nao foi possivel gerar a pre-visualizacao.",
        "btn_apply_profile": "Aplicar no processamento geral",
        "report_title": "Antes / depois",
        "report_file": "Arquivo",
        "report_before_i": "Antes (I)",
        "report_before_lra": "Antes (LRA)",
        "report_before_tp": "Antes (TP)",
        "report_after_i": "Depois (I)",
        "report_after_lra": "Depois (LRA)",
        "report_after_tp": "Depois (TP)",
        "btn_export_csv": "CSV",
        "btn_export_txt": "TXT",
        "btn_clear_report": "Limpar",
        "report_filename_base": "relatório",
        "group_summary": "Resumo",
        "summary_no_data": "Sem dados",
        "summary_text": "Total {total} · ok {ok} · erro {fail} · {ratio:.0f}%\nLUFS médio: {avg_before:.2f} -> {avg_after:.2f} (D {delta:+.2f})",
        "msg_attention": "Atenção",
        "msg_success": "Sucesso",
        "msg_error": "Erro",
        "msg_info": "Info",
        "msg_confirm": "Confirmar",
        "dialog_close": "Fechar",
        "settings_title": "Configuração",
        "settings_input": "Origem:",
        "settings_output": "Destino:",
        "settings_browse": "Explorar...",
        "settings_save": "Salvar",
        "settings_cancel": "Cancelar",
        "pick_input_folder": "Selecionar pasta de origem",
        "pick_output_folder": "Selecionar pasta de destino",
        "pick_reference_video": "Selecionar vídeo de referência",
        "video_filter": "Vídeos (*.mp4 *.mkv *.mov *.avi *.flv *.webm);;Todos (*.*)",
        "all_filter": "Todos (*.*)",
        "save_csv": "Salvar CSV",
        "save_txt": "Salvar TXT",
        "csv_filter": "CSV (*.csv);;Todos (*.*)",
        "txt_filter": "Texto (*.txt);;Todos (*.*)",
        "manual_title": "Manual",
        "manual_text": "Guia rápido:\n1. Selecione origem e destino.\n2. Marque vídeos.\n3. Ajuste LUFS/LRA/TP.\n4. Inicie e revise o Relatório.",
        "about_title": "Sobre",
        "about_text": "FFmpeg Master Vol Normalizer v{version}\n\nNormalizador de volume para vídeo/áudio com ffmpeg loudnorm.\nInterface: PyQt6\nLicença: MIT",
        "support_title": "Apoiar o projeto",
        "support_heading": "💙 Apoie o projeto",
        "support_message": "Se esta ferramenta foi útil para você e ajudou no seu trabalho, considere uma contribuição voluntária para apoiar a evolução e a manutenção do projeto.",
        "support_note": "✨ Sua ajuda contribui para melhorias, correções e novos recursos.",
        "support_target": "🔗 Transferência via PIX (chave): {target}",
        "support_scan_hint": "📱 Escaneie o QR Code ou copie a chave PIX abaixo.",
        "support_open": "Copiar chave PIX",
        "support_qr_error": "Não foi possível gerar o código QR agora.",
        "support_pix_copied": "Chave PIX copiada para a área de transferência.",
        "deps_missing_title": "Dependências ausentes",
        "deps_missing_text": "Dependências obrigatórias ausentes:\n\n{missing}\n\nAbrir site de download do FFmpeg?",
        "cannot_start_without_ffmpeg": "Não é possível iniciar sem FFmpeg instalado.",
        "exit_title": "Sair",
        "exit_text": "Deseja sair?",
        "busy_title": "Aviso",
        "busy_text": "O aplicativo está processando. Cancele ou aguarde finalizar.",
        "language_spanish": "Espanhol",
        "language_english": "Inglês",
        "language_portuguese": "Português",
        "logs_title": "Logs",
        "logs_empty": "Ainda não há registros.",
        "error_reading_logs": "Erro ao ler logs: {error}",
        "errors_report_title": "Relatório de Erros",
        "errors_report_ok": "Nenhum erro encontrado.",
        "errors_report_header": "RELATÓRIO DE ERROS\n{line}\nTotal: {count}\n\n{items}",
        "update_deps_question": "Atualizar PyQt6 via pip?",
        "update_deps_ok": "Dependências atualizadas. Reinicie o aplicativo.",
        "update_deps_fail": "Não foi possível atualizar dependências.\n\n{error}",
        "deps_title": "Dependências",
        "deps_all_ok": "{info}\n\nTudo certo.",
        "deps_missing": "{info}\n\nDependências ausentes.",
        "clean_cache_question": "Excluir arquivos temporários?",
        "clean_cache_result": "{count} arquivos excluídos.",
        "restore_config_question": "Restaurar configuração padrão?",
        "restore_config_done": "Configuração restaurada. Reinicie o aplicativo.",
        "settings_saved": "Configuração salva.",
        "download_ffmpeg_title": "Baixar FFmpeg",
        "download_ffmpeg_question": "Abrir site de download do FFmpeg?",
        "version_title": "Versão",
        "version_text": "Versão atual: {version}\nVerificado: {checked}\n\nVocê está usando a versão mais recente.",        "update_available_title": "Atualização disponível",
        "update_available_message": "Versão {latest} disponível (você tem {current})\n\nBaixá-la?",
        "update_check_error": "Não foi possível verificar atualizações. Tente mais tarde.",
        "update_up_to_date": "Você já tem a versão mais recente ({version}).",
        "btn_download": "Baixar",
        "btn_ignore": "Ignorar",
        "preset_label": "Preset:",
        "preset_custom": "Custom",
        "preset_applied": "Preset {name} aplicado ({lufs} LUFS · LRA {lra} · TP {tp} dB)",
        "gpu_label": "GPU accel:",
        "gpu_detected": "{method} detectado",
        "gpu_none": "Não disponível",
        "gpu_enabled_hint": "Acelera a leitura de vídeo com hardware",
        "parallel_label": "Paralelo:",
        "parallel_hint": "{workers} processos simultâneos",
        "processing_parallel": "Processando em paralelo ({workers}): {done}/{total}",
        "item_pending": "Pendente",
        "processing_item": "Processando {index}/{total}: {name}...",
        "status_analyzing": "Analisando...",
        "status_normalizing": "Normalizando...",
        "status_completed": "Concluído",
        "status_timeout": "Timeout",
        "status_canceled": "Cancelado",
        "status_error": "Erro",
        "status_success": "Sucesso",
        "status_finished": "Finalizado",
        "finished_counts": "Processados: {ok}\nErros: {fail}",
        "profile_analyzing": "Analisando...",
        "analyzer_saved": "Vídeo analisado. Perfil salvo.",
        "analysis_error_title": "Erro de análise",
        "no_videos_selected": "Selecione pelo menos um vídeo para normalizar.",
        "profile_applied": "Perfil de áudio aplicado com sucesso.\n\nLUFS: {lufs} · LRA: {lra} · TP: {tp} dB",
        "profile_info_loaded": "VÍDEO ANALISADO\n{line}\nArquivo: {filename}\nData: {date}\n\nPARÂMETROS DETECTADOS\n{line}\nInput Loudness (I): {input_i:.2f} LUFS\nLoudness Range (LRA): {input_lra:.2f} LU\nTrue Peak (TP): {input_tp:.2f} dB\nThreshold: {input_thresh:.2f} dB\nTarget Offset: {target_offset:.2f}\n\nPronto para usar como referência",
        "profile_info_empty": "SEM PERFIL CARREGADO\n\n1. Selecione um vídeo\n2. Clique em Extrair perfil\n3. Aguarde o resultado\n4. Aplique o perfil no processamento geral",
        "manual_text_full": "NORMALIZADOR DE ÁUDIO · MANUAL PROFISSIONAL\n============================================================\n\n1) O que este aplicativo faz\nNormaliza o volume de lotes de vídeos para manter áudio consistente,\nusando FFmpeg e processamento loudnorm baseado em LUFS.\n\n2) Fluxo recomendado\n1. Na aba Normalizar, escolha pasta de origem.\n2. Marque os vídeos para processar.\n3. Escolha pasta de destino.\n4. Ajuste LUFS / LRA / TP.\n5. Inicie o processamento e aguarde.\n6. Revise a aba Relatório e exporte CSV/TXT.\n\n3) Parâmetros\n- LUFS: loudness percebido (alvo comum web: -14).\n- LRA: faixa dinâmica (menor = mais uniforme, maior = mais natural).\n- TP: pico máximo verdadeiro para evitar clipping (recomendado: -1.5 dB).\n\n4) Perfil de referência\n1. Abra a aba Perfil.\n2. Escolha vídeo de referência.\n3. Extraia o perfil.\n4. Aplique no processamento geral.\n5. Volte para Normalizar e processe o lote.\n\n5) Relatório\nMostra antes/depois por vídeo (I, LRA, TP), status por arquivo\ne resumo global com média LUFS e taxa de sucesso.\n\n6) Utilitários\n- Configuração de caminhos padrão.\n- Alternância de tema claro/escuro.\n- Visualização de logs e relatório de erros.\n- Limpeza de cache temporário.\n\n7) Problemas comuns\n- FFmpeg não encontrado: instalar e adicionar ao PATH.\n- Sem vídeos listados: verificar formatos suportados.\n- Erro ao exportar: verificar permissão de escrita.\n- Timeout: processar em lotes menores.\n\n8) Boas práticas\n- Use pasta de destino diferente da origem.\n- Teste com 1-2 vídeos antes do lote completo.\n- Para web, comece com -14 LUFS, LRA moderado e TP -1.5 dB.\n\n9) Resultado esperado\nVolume final consistente, profissional e confortável para reprodução contínua.",
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    table = TRANSLATIONS.get(lang, TRANSLATIONS["es"])
    value = table.get(key, TRANSLATIONS["es"].get(key, key))
    if kwargs:
        try:
            return value.format(**kwargs)
        except Exception:
            return value
    return value
