"""Simple i10n/i18n runtime translations for the UI."""

from __future__ import annotations


SUPPORTED_LANGUAGES = {
    "es": "Español",
    "en": "English",
    "pt": "Português",
}


TRANSLATIONS = {
    "es": {
        "app_title": "Normalizador Audio",
        "header_subtitle": "Normalización LUFS profesional con FFmpeg",
        "menu_file": "Archivo",
        "menu_tools": "Herramientas",
        "menu_help": "Ayuda",
        "menu_language": "Idioma",
        "action_update_deps": "Actualizar dependencias",
        "action_check_deps": "Verificar dependencias",
        "action_clean_cache": "Limpiar caché",
        "action_restore": "Restaurar configuración",
        "action_exit": "Salir",
        "action_logs": "Ver logs",
        "action_errors": "Reporte de errores",
        "action_settings": "Configuración...",
        "action_theme": "Cambiar tema",
        "action_manual": "Manual",
        "action_support_project": "Ayuda al proyecto",
        "action_ffmpeg": "Instalar FFmpeg",
        "action_updates": "Verificar actualizaciones",
        "action_about": "Acerca de",
        "tab_normalize": "Normalizar",
        "tab_profile": "Perfil",
        "tab_report": "Reporte",
        "btn_input": "Origen",
        "btn_output": "Destino",
        "btn_clear_output": "Limpiar destino",
        "btn_clear_list": "Limpiar lista",
        "label_input_empty": "Origen: -",
        "label_output_empty": "Destino: -",
        "label_input_value": "Origen: {name}",
        "label_output_value": "Destino: {name}",
        "label_videos": "Videos",
        "label_videos_hint": "Arrastra · doble clic o Espacio para seleccionar",
        "table_selected": "Selección",
        "table_file": "Archivo",
        "table_size": "Tamaño",
        "table_status": "Estado",
        "btn_select_all": "Todo",
        "btn_select_none": "Nada",
        "label_progress": "Progreso",
        "btn_start": "Iniciar",
        "btn_cancel": "Cancelar",
        "status_ready": "Listo",
        "status_canceling": "Cancelando...",
        "profile_title": "Perfil de audio",
        "profile_subtitle": "Elige un video de referencia, extrae su perfil y aplícalo al procesamiento general",
        "profile_no_file": "Sin archivo",
        "btn_pick_video": "Elegir...",
        "btn_analyze": "Extraer perfil",
        "btn_clear_profile": "Borrar perfil",
        "group_output": "Salida",
        "waveform_group": "Waveform",
        "waveform_empty": "Selecciona un video para ver la forma de onda.",
        "waveform_loading": "Generando waveform...",
        "waveform_unavailable": "No se pudo generar la previsualizacion.",
        "btn_apply_profile": "Aplicar al procesamiento general",
        "report_title": "Antes / después",
        "report_file": "Archivo",
        "report_before_i": "Antes (I)",
        "report_before_lra": "Antes (LRA)",
        "report_before_tp": "Antes (TP)",
        "report_after_i": "Después (I)",
        "report_after_lra": "Después (LRA)",
        "report_after_tp": "Después (TP)",
        "btn_export_csv": "CSV",
        "btn_export_txt": "TXT",
        "btn_clear_report": "Limpiar",
        "report_filename_base": "reporte",
        "group_summary": "Resumen",
        "summary_no_data": "Sin datos",
        "summary_text": "Total {total} · ok {ok} · error {fail} · {ratio:.0f}%\nLUFS medio: {avg_before:.2f} -> {avg_after:.2f} (D {delta:+.2f})",
        "msg_attention": "Atención",
        "msg_success": "Éxito",
        "msg_error": "Error",
        "msg_info": "Info",
        "msg_confirm": "Confirmar",
        "dialog_close": "Cerrar",
        "settings_title": "Configuración",
        "settings_input": "Origen:",
        "settings_output": "Destino:",
        "settings_browse": "Explorar...",
        "settings_save": "Guardar",
        "settings_cancel": "Cancelar",
        "pick_input_folder": "Seleccionar carpeta de origen",
        "pick_output_folder": "Seleccionar carpeta de destino",
        "pick_reference_video": "Seleccionar video de referencia",
        "video_filter": "Videos (*.mp4 *.mkv *.mov *.avi *.flv *.webm);;Todos (*.*)",
        "all_filter": "Todos (*.*)",
        "save_csv": "Guardar CSV",
        "save_txt": "Guardar TXT",
        "csv_filter": "CSV (*.csv);;Todos (*.*)",
        "txt_filter": "Texto (*.txt);;Todos (*.*)",
        "manual_title": "Manual",
        "manual_text": "Guía rápida:\n1. Selecciona Origen y Destino.\n2. Elige un preset o ajusta LUFS/LRA/TP.\n3. (Opcional) Usa Perfil para extraer y aplicar una referencia.\n4. Inicia el procesamiento y monitorea estados por archivo.\n5. Revisa Reporte y exporta CSV/TXT.\n6. Si falta FFmpeg, usa Ayuda > Instalar FFmpeg.",
        "about_title": "Acerca de",
        "about_text": "FFmpeg Master Vol Normalizer v{version}\n\nNormalizador de volumen para video/audio con ffmpeg loudnorm.\nInterfaz: PyQt6\nLicencia: MIT",
        "support_title": "Ayuda al proyecto",
        "support_heading": "💙 Apoya el proyecto",
        "support_message": "Si esta herramienta te ha resultado útil y te ha ayudado en tu trabajo, puedes apoyar su desarrollo y mantenimiento con una contribución voluntaria.",
        "support_note": "✨ Tu apoyo ayuda a mantener mejoras, correcciones y nuevas funciones.",
        "support_target": "🔗 Enlace de pago (Wise): {target}",
        "support_scan_hint": "📱 Escanea el código QR o usa el botón de acción.",
        "support_open": "Abrir enlace de pago",
        "support_copy": "Copiar enlace",
        "support_link_copied": "Enlace de pago copiado al portapapeles.",
        "support_qr_error": "No se pudo generar el código QR en este momento.",
        "deps_missing_title": "Dependencias faltantes",
        "deps_missing_text": "Faltan dependencias necesarias:\n\n{missing}\n\n¿Instalar FFmpeg automaticamente con winget en una consola?",
        "deps_installing_console": "Se abrira una consola para instalar FFmpeg con winget. Espera a que termine y vuelve a esta ventana.",
        "deps_install_ok": "FFmpeg se instalo correctamente. La aplicacion continuara.",
        "ffmpeg_already_installed": "FFmpeg ya esta instalado en el sistema. No es necesario instalarlo nuevamente.",
        "deps_install_fail": "No se pudo instalar FFmpeg automaticamente.\n\nDetalle: {error}",
        "deps_install_fail_unknown": "Error desconocido durante la instalacion.",
        "cannot_start_without_ffmpeg": "No se puede iniciar sin FFmpeg instalado.",
        "exit_title": "Salir",
        "exit_text": "¿Deseas salir?",
        "busy_title": "Advertencia",
        "busy_text": "La aplicación está procesando. Cancela o espera a que termine.",
        "language_spanish": "Español",
        "language_english": "English",
        "language_portuguese": "Portugués",
        "logs_title": "Registros",
        "logs_empty": "No hay registros aún.",
        "error_reading_logs": "Error leyendo logs: {error}",
        "errors_report_title": "Reporte de Errores",
        "errors_report_ok": "No se encontraron errores.",
        "errors_report_header": "REPORTE DE ERRORES\n{line}\nTotal: {count}\n\n{items}",
        "update_deps_question": "¿Actualizar PyQt6 vía pip?",
        "update_deps_ok": "Dependencias actualizadas. Reinicia la aplicación.",
        "update_deps_fail": "No se pudieron actualizar dependencias.\n\n{error}",
        "deps_title": "Dependencias",
        "deps_all_ok": "{info}\n\nTodo correcto.",
        "deps_missing": "{info}\n\nFaltan dependencias.",
        "clean_cache_question": "¿Eliminar archivos temporales?",
        "clean_cache_result": "{count} archivos eliminados.",
        "restore_config_question": "¿Restaurar configuración por defecto?",
        "restore_config_done": "Configuración restaurada. Reinicia la aplicación.",
        "settings_saved": "Configuración guardada.",
        "download_ffmpeg_title": "Instalar FFmpeg",
        "download_ffmpeg_question": "¿Instalar FFmpeg automaticamente con winget en una consola?",
        "version_title": "Versión",
        "version_text": "Versión actual: {version}\nVerificado: {checked}\n\nEstás usando la última versión disponible.",
        "update_available_title": "Actualización disponible",
        "update_available_message": "Versión {latest} disponible (tienes {current})\n\n¿Descargarla?",
        "update_check_error": "No se pudo verificar actualizaciones. Intenta más tarde.",
        "update_up_to_date": "Ya tienes la última versión ({version}).",
        "btn_download": "Descargar",
        "btn_ignore": "Ignorar",
        "preset_label": "Preset:",
        "preset_custom": "Custom",
        "preset_applied": "Preset {name} aplicado ({lufs} LUFS · LRA {lra} · TP {tp} dB)",
        "gpu_label": "GPU accel:",
        "gpu_detected": "{method} detectado",
        "gpu_none": "No disponible",
        "gpu_enabled_hint": "Acelera la lectura de video con hardware",
        "parallel_label": "Paralelo:",
        "parallel_hint": "{workers} procesos simultáneos",
        "processing_parallel": "Procesando en paralelo ({workers}): {done}/{total}",
        "item_pending": "Pendiente",
        "processing_item": "Procesando {index}/{total}: {name}...",
        "status_analyzing": "Analizando...",
        "status_normalizing": "Normalizando...",
        "status_completed": "Completado",
        "status_timeout": "Timeout",
        "status_canceled": "Cancelado",
        "status_error": "Error",
        "status_success": "Éxito",
        "status_finished": "Finalizado",
        "finished_counts": "Procesados: {ok}\nErrores: {fail}",
        "profile_analyzing": "Analizando...",
        "analyzer_saved": "Video analizado. Perfil guardado.",
        "analysis_error_title": "Error de análisis",
        "no_videos_selected": "Debes seleccionar al menos un video para normalizar.",
        "profile_applied": "Perfil de audio aplicado correctamente.\n\nLUFS: {lufs} · LRA: {lra} · TP: {tp} dB",
        "profile_info_loaded": "VIDEO ANALIZADO\n{line}\nArchivo: {filename}\nFecha: {date}\n\nPARÁMETROS DETECTADOS\n{line}\nInput Loudness (I): {input_i:.2f} LUFS\nLoudness Range (LRA): {input_lra:.2f} LU\nTrue Peak (TP): {input_tp:.2f} dB\nThreshold: {input_thresh:.2f} dB\nTarget Offset: {target_offset:.2f}\n\nListo para usar como referencia",
        "profile_info_empty": "SIN PERFIL CARGADO\n\n1. Selecciona un video de referencia\n2. Haz clic en Extraer perfil\n3. Espera el resultado\n4. Aplica el perfil al procesamiento general",
        "manual_text_full": "🎛️ NORMALIZADOR AUDIO · MANUAL PROFESIONAL\n============================================================\n\n📌 1) Objetivo de la aplicación\nNormalizador Audio estandariza el volumen de lotes de video para obtener\nun nivel de escucha consistente y profesional usando FFmpeg + loudnorm (LUFS).\n\n✅ Ideal para:\n• Contenido web (YouTube, cursos, redes sociales)\n• Entregables corporativos\n• Bibliotecas de video con volumen desigual\n\n🧩 2) Interfaz y funciones principales\nLa app se organiza en 3 pestañas:\n\n1. 🎚️ Normalizar\n• Selección de carpeta de origen y destino\n• Lista de videos con estado por archivo\n• Presets rápidos: YouTube, Netflix, Spotify, Podcast, Custom\n• Ajustes manuales de LUFS, LRA y TP\n• Aceleración GPU opcional (si el equipo la soporta)\n• Procesamiento en paralelo (múltiples trabajos simultáneos)\n\n2. 🧪 Perfil\n• Selección de video de referencia\n• Extracción automática de perfil de audio\n• Vista de waveform (forma de onda)\n• Aplicación del perfil al flujo general\n\n3. 📊 Reporte\n• Métricas antes/después: I, LRA, TP\n• Estado por archivo (éxito, error, cancelado, timeout)\n• Exportación a CSV y TXT\n• Resumen global con tasa de éxito\n\n🚀 3) Flujo recomendado paso a paso\n1. En la pestaña Normalizar, pulsa Origen y selecciona tu carpeta de entrada.\n2. Pulsa Destino y elige una carpeta distinta para salida.\n3. Marca los videos a procesar (drag & drop, doble clic o Espacio).\n4. Elige un preset o ajusta LUFS/LRA/TP manualmente.\n5. (Opcional) Activa GPU accel y define el nivel de Paralelo.\n6. Pulsa Iniciar y monitorea el progreso por archivo.\n7. Revisa la pestaña Reporte y exporta resultados si lo necesitas.\n\n🎯 4) Guía rápida de parámetros\n• LUFS: volumen percibido global.\n  Recomendación inicial web: -14 LUFS.\n• LRA: rango dinámico.\n  Menor valor = sonido más uniforme; mayor = más natural.\n• TP (True Peak): pico máximo para evitar clipping.\n  Recomendado: -1.5 dB.\n\n🧠 5) Uso del Perfil de referencia\n1. Abre la pestaña Perfil.\n2. Pulsa Elegir... y selecciona un video con audio de buena calidad.\n3. Pulsa Extraer perfil.\n4. Verifica los valores detectados y la waveform.\n5. Pulsa Aplicar al procesamiento general.\n6. Vuelve a Normalizar y ejecuta el lote completo.\n\n🛠️ 6) Menús y utilidades\n📂 Archivo\n• Actualizar dependencias (PyQt6)\n• Verificar dependencias\n• Limpiar caché\n• Restaurar configuración\n\n🧰 Herramientas\n• Ver logs\n• Reporte de errores\n• Configuración\n• Cambiar tema\n\n❓ Ayuda\n• Manual\n• Ayuda al proyecto\n• Instalar FFmpeg\n• Verificar actualizaciones\n\n🔐 7) Gestión automática de FFmpeg (nuevo)\nLa aplicación valida FFmpeg al iniciar.\n\nSi NO está instalado:\n• Ofrece instalación automática con winget en una consola.\n• Al finalizar, vuelve a validar disponibilidad.\n\nDesde Ayuda > Instalar FFmpeg:\n• Si FFmpeg ya existe en el sistema, verás un mensaje indicando que\n  no es necesario instalarlo de nuevo.\n• Si falta, se ejecuta el instalador automático.\n\n⚠️ 8) Solución de problemas\n• FFmpeg no aparece tras instalarse: cierra y abre la app nuevamente.\n• Sin videos en lista: revisa formatos compatibles y carpeta origen.\n• Error al exportar: verifica permisos de escritura en destino.\n• Timeout en procesos largos: reduce el paralelo o divide en lotes.\n• GPU inestable: desactiva GPU accel y procesa por CPU.\n\n💡 9) Buenas prácticas profesionales\n• Usa siempre destino distinto al origen.\n• Haz una prueba con 1-2 archivos antes del lote final.\n• Mantén presets para velocidad y usa Custom para casos especiales.\n• Revisa el reporte final para trazabilidad y control de calidad.\n\n🏁 10) Resultado esperado\nAudio homogéneo, más cómodo de escuchar, con estándar técnico\ny calidad consistente en todo el lote.",
    },
    "en": {
        "app_title": "Audio Normalizer",
        "header_subtitle": "Professional LUFS normalization with FFmpeg",
        "menu_file": "File",
        "menu_tools": "Tools",
        "menu_help": "Help",
        "menu_language": "Language",
        "action_update_deps": "Update dependencies",
        "action_check_deps": "Check dependencies",
        "action_clean_cache": "Clean cache",
        "action_restore": "Restore settings",
        "action_exit": "Exit",
        "action_logs": "View logs",
        "action_errors": "Error report",
        "action_settings": "Settings...",
        "action_theme": "Toggle theme",
        "action_manual": "Manual",
        "action_support_project": "Support the project",
        "action_ffmpeg": "Install FFmpeg",
        "action_updates": "Check updates",
        "action_about": "About",
        "tab_normalize": "Normalize",
        "tab_profile": "Profile",
        "tab_report": "Report",
        "btn_input": "Input",
        "btn_output": "Output",
        "btn_clear_output": "Clear output",
        "btn_clear_list": "Clear list",
        "label_input_empty": "Input: -",
        "label_output_empty": "Output: -",
        "label_input_value": "Input: {name}",
        "label_output_value": "Output: {name}",
        "label_videos": "Videos",
        "label_videos_hint": "Drag · double click or Space to select",
        "table_selected": "Select",
        "table_file": "File",
        "table_size": "Size",
        "table_status": "Status",
        "btn_select_all": "All",
        "btn_select_none": "None",
        "label_progress": "Progress",
        "btn_start": "Start",
        "btn_cancel": "Cancel",
        "status_ready": "Ready",
        "status_canceling": "Canceling...",
        "profile_title": "Audio profile",
        "profile_subtitle": "Choose a reference video, extract its profile and apply it to general processing",
        "profile_no_file": "No file",
        "btn_pick_video": "Choose...",
        "btn_analyze": "Extract profile",
        "btn_clear_profile": "Clear profile",
        "group_output": "Output",
        "waveform_group": "Waveform",
        "waveform_empty": "Select a video to preview its waveform.",
        "waveform_loading": "Generating waveform...",
        "waveform_unavailable": "Could not generate waveform preview.",
        "btn_apply_profile": "Apply to general processing",
        "report_title": "Before / after",
        "report_file": "File",
        "report_before_i": "Before (I)",
        "report_before_lra": "Before (LRA)",
        "report_before_tp": "Before (TP)",
        "report_after_i": "After (I)",
        "report_after_lra": "After (LRA)",
        "report_after_tp": "After (TP)",
        "btn_export_csv": "CSV",
        "btn_export_txt": "TXT",
        "btn_clear_report": "Clear",
        "report_filename_base": "report",
        "group_summary": "Summary",
        "summary_no_data": "No data",
        "summary_text": "Total {total} · ok {ok} · fail {fail} · {ratio:.0f}%\nAvg LUFS: {avg_before:.2f} -> {avg_after:.2f} (D {delta:+.2f})",
        "msg_attention": "Attention",
        "msg_success": "Success",
        "msg_error": "Error",
        "msg_info": "Info",
        "msg_confirm": "Confirm",
        "dialog_close": "Close",
        "settings_title": "Settings",
        "settings_input": "Input:",
        "settings_output": "Output:",
        "settings_browse": "Browse...",
        "settings_save": "Save",
        "settings_cancel": "Cancel",
        "pick_input_folder": "Select input folder",
        "pick_output_folder": "Select output folder",
        "pick_reference_video": "Select reference video",
        "video_filter": "Videos (*.mp4 *.mkv *.mov *.avi *.flv *.webm);;All (*.*)",
        "all_filter": "All (*.*)",
        "save_csv": "Save CSV",
        "save_txt": "Save TXT",
        "csv_filter": "CSV (*.csv);;All (*.*)",
        "txt_filter": "Text (*.txt);;All (*.*)",
        "manual_title": "Manual",
        "manual_text": "Quick guide:\n1. Select Input and Output folders.\n2. Pick a preset or adjust LUFS/LRA/TP manually.\n3. (Optional) Use Profile to extract and apply a reference.\n4. Start processing and monitor per-file status.\n5. Review Report and export CSV/TXT.\n6. If FFmpeg is missing, use Help > Install FFmpeg.",
        "about_title": "About",
        "about_text": "FFmpeg Master Vol Normalizer v{version}\n\nVolume normalizer for video/audio with ffmpeg loudnorm.\nUI: PyQt6\nLicense: MIT",
        "support_title": "Support the project",
        "support_heading": "💙 Support the project",
        "support_message": "If this tool has been useful and has helped your workflow, consider making a voluntary contribution to support ongoing development and maintenance.",
        "support_note": "✨ Your support helps fund improvements, fixes, and new features.",
        "support_target": "🔗 Payment link (Wise): {target}",
        "support_scan_hint": "📱 Scan the QR code or use the action button.",
        "support_open": "Open payment link",
        "support_copy": "Copy link",
        "support_link_copied": "Payment link copied to the clipboard.",
        "support_qr_error": "The QR code could not be generated right now.",
        "deps_missing_title": "Missing dependencies",
        "deps_missing_text": "Required dependencies are missing:\n\n{missing}\n\nInstall FFmpeg automatically with winget in a console window?",
        "deps_installing_console": "A console window will open to install FFmpeg with winget. Wait for it to finish and return to this app.",
        "deps_install_ok": "FFmpeg was installed successfully. The app will continue.",
        "ffmpeg_already_installed": "FFmpeg is already installed on this system. No installation is needed.",
        "deps_install_fail": "FFmpeg could not be installed automatically.\n\nDetails: {error}",
        "deps_install_fail_unknown": "Unknown error during installation.",
        "cannot_start_without_ffmpeg": "Cannot start without FFmpeg installed.",
        "exit_title": "Exit",
        "exit_text": "Do you want to exit?",
        "busy_title": "Warning",
        "busy_text": "The app is processing. Cancel or wait for completion.",
        "language_spanish": "Spanish",
        "language_english": "English",
        "language_portuguese": "Portuguese",
        "logs_title": "Logs",
        "logs_empty": "No logs yet.",
        "error_reading_logs": "Error reading logs: {error}",
        "errors_report_title": "Error Report",
        "errors_report_ok": "No errors found.",
        "errors_report_header": "ERROR REPORT\n{line}\nTotal: {count}\n\n{items}",
        "update_deps_question": "Update PyQt6 using pip?",
        "update_deps_ok": "Dependencies updated. Restart the app.",
        "update_deps_fail": "Dependencies could not be updated.\n\n{error}",
        "deps_title": "Dependencies",
        "deps_all_ok": "{info}\n\nAll good.",
        "deps_missing": "{info}\n\nMissing dependencies.",
        "clean_cache_question": "Delete temporary files?",
        "clean_cache_result": "{count} files deleted.",
        "restore_config_question": "Restore default settings?",
        "restore_config_done": "Settings restored. Restart the app.",
        "settings_saved": "Settings saved.",
        "download_ffmpeg_title": "Install FFmpeg",
        "download_ffmpeg_question": "Install FFmpeg automatically with winget in a console window?",
        "version_title": "Version",
        "version_text": "Current version: {version}\nChecked: {checked}\n\nYou are using the latest available version.",        "update_available_title": "Update available",
        "update_available_message": "Version {latest} available (you have {current})\n\nDownload it?",
        "update_check_error": "Could not check for updates. Try again later.",
        "update_up_to_date": "You already have the latest version ({version}).",
        "btn_download": "Download",
        "btn_ignore": "Ignore",
        "preset_label": "Preset:",
        "preset_custom": "Custom",
        "preset_applied": "Preset {name} applied ({lufs} LUFS · LRA {lra} · TP {tp} dB)",
        "gpu_label": "GPU accel:",
        "gpu_detected": "{method} detected",
        "gpu_none": "Not available",
        "gpu_enabled_hint": "Accelerates video reading with hardware",
        "parallel_label": "Parallel:",
        "parallel_hint": "{workers} simultaneous jobs",
        "processing_parallel": "Parallel processing ({workers}): {done}/{total}",
        "item_pending": "Pending",
        "processing_item": "Processing {index}/{total}: {name}...",
        "status_analyzing": "Analyzing...",
        "status_normalizing": "Normalizing...",
        "status_completed": "Completed",
        "status_timeout": "Timeout",
        "status_canceled": "Canceled",
        "status_error": "Error",
        "status_success": "Success",
        "status_finished": "Finished",
        "finished_counts": "Processed: {ok}\nErrors: {fail}",
        "profile_analyzing": "Analyzing...",
        "analyzer_saved": "Video analyzed. Profile saved.",
        "analysis_error_title": "Analysis error",
        "no_videos_selected": "You must select at least one video to normalize.",
        "profile_applied": "Audio profile applied successfully.\n\nLUFS: {lufs} · LRA: {lra} · TP: {tp} dB",
        "profile_info_loaded": "ANALYZED VIDEO\n{line}\nFile: {filename}\nDate: {date}\n\nDETECTED PARAMETERS\n{line}\nInput Loudness (I): {input_i:.2f} LUFS\nLoudness Range (LRA): {input_lra:.2f} LU\nTrue Peak (TP): {input_tp:.2f} dB\nThreshold: {input_thresh:.2f} dB\nTarget Offset: {target_offset:.2f}\n\nReady to use as reference",
        "profile_info_empty": "NO PROFILE LOADED\n\n1. Select a video\n2. Click Extract profile\n3. Wait for the result\n4. Apply profile to general processing",
        "manual_text_full": "🎛️ AUDIO NORMALIZER · PROFESSIONAL MANUAL\n============================================================\n\n📌 1) Application purpose\nAudio Normalizer standardizes loudness across video batches to deliver\nconsistent and professional playback using FFmpeg + loudnorm (LUFS).\n\n✅ Best suited for:\n• Web publishing (YouTube, social media, e-learning)\n• Corporate media delivery\n• Large video libraries with uneven volume\n\n🧩 2) Interface overview\nThe app is organized into 3 tabs:\n\n1. 🎚️ Normalize\n• Input and output folder selection\n• Video list with per-file status\n• Quick presets: YouTube, Netflix, Spotify, Podcast, Custom\n• Manual LUFS / LRA / TP controls\n• Optional GPU acceleration when available\n• Parallel processing control (multiple simultaneous jobs)\n\n2. 🧪 Profile\n• Reference video selection\n• Automatic audio profile extraction\n• Waveform preview\n• Apply profile to global processing settings\n\n3. 📊 Report\n• Before/after metrics: I, LRA, TP\n• Per-file state (success, error, canceled, timeout)\n• CSV and TXT export\n• Global summary with success rate\n\n🚀 3) Recommended workflow\n1. In Normalize, click Input and choose your source folder.\n2. Click Output and select a different target folder.\n3. Select videos to process (drag & drop, double click, or Space).\n4. Pick a preset or tune LUFS/LRA/TP manually.\n5. (Optional) Enable GPU accel and set Parallel jobs.\n6. Click Start and monitor per-file progress.\n7. Open Report and export CSV/TXT when needed.\n\n🎯 4) Parameter quick guide\n• LUFS: overall perceived loudness.\n  Typical web baseline: -14 LUFS.\n• LRA: dynamic range.\n  Lower = tighter and more uniform; higher = more natural.\n• TP (True Peak): maximum peak ceiling to prevent clipping.\n  Recommended baseline: -1.5 dB.\n\n🧠 5) Reference profile workflow\n1. Open the Profile tab.\n2. Click Choose... and select a high-quality reference video.\n3. Click Extract profile.\n4. Review detected values and waveform preview.\n5. Click Apply to general processing.\n6. Return to Normalize and run the full batch.\n\n🛠️ 6) Menus and utilities\n📂 File\n• Update dependencies (PyQt6)\n• Check dependencies\n• Clean cache\n• Restore configuration\n\n🧰 Tools\n• View logs\n• Error report\n• Settings\n• Toggle theme\n\n❓ Help\n• Manual\n• Support the project\n• Install FFmpeg\n• Check updates\n\n🔐 7) Automatic FFmpeg management (new)\nThe application validates FFmpeg at startup.\n\nIf FFmpeg is missing:\n• The app offers automatic installation through winget in a console window.\n• After installation, availability is validated again.\n\nFrom Help > Install FFmpeg:\n• If FFmpeg is already installed, the app shows a message that no action\n  is required.\n• If missing, automatic installation flow starts.\n\n⚠️ 8) Troubleshooting\n• FFmpeg not visible right after install: close and reopen the app.\n• Empty video list: verify source folder and supported formats.\n• Export failure: check write permissions in output directory.\n• Timeout on heavy jobs: reduce parallelism or split the batch.\n• GPU instability: disable GPU accel and use CPU fallback.\n\n💡 9) Professional best practices\n• Always use a different output folder from input.\n• Run a 1-2 file validation pass before large batches.\n• Use presets for speed; use Custom for special delivery specs.\n• Review final reports for traceability and quality control.\n\n🏁 10) Expected outcome\nConsistent, listener-friendly loudness with technical compliance\nand production-ready quality across the full batch.",
    },
    "pt": {
        "app_title": "Normalizador de Áudio",
        "header_subtitle": "Normalização LUFS profissional com FFmpeg",
        "menu_file": "Arquivo",
        "menu_tools": "Ferramentas",
        "menu_help": "Ajuda",
        "menu_language": "Idioma",
        "action_update_deps": "Atualizar dependências",
        "action_check_deps": "Verificar dependências",
        "action_clean_cache": "Limpar cache",
        "action_restore": "Restaurar configuração",
        "action_exit": "Sair",
        "action_logs": "Ver logs",
        "action_errors": "Relatório de erros",
        "action_settings": "Configuração...",
        "action_theme": "Alternar tema",
        "action_manual": "Manual",
        "action_support_project": "Apoiar o projeto",
        "action_ffmpeg": "Instalar FFmpeg",
        "action_updates": "Verificar atualizações",
        "action_about": "Sobre",
        "tab_normalize": "Normalizar",
        "tab_profile": "Perfil",
        "tab_report": "Relatório",
        "btn_input": "Origem",
        "btn_output": "Destino",
        "btn_clear_output": "Limpar destino",
        "btn_clear_list": "Limpar lista",
        "label_input_empty": "Origem: -",
        "label_output_empty": "Destino: -",
        "label_input_value": "Origem: {name}",
        "label_output_value": "Destino: {name}",
        "label_videos": "Vídeos",
        "label_videos_hint": "Arraste · duplo clique ou Espaço para selecionar",
        "table_selected": "Seleção",
        "table_file": "Arquivo",
        "table_size": "Tamanho",
        "table_status": "Status",
        "btn_select_all": "Tudo",
        "btn_select_none": "Nada",
        "label_progress": "Progresso",
        "btn_start": "Iniciar",
        "btn_cancel": "Cancelar",
        "status_ready": "Pronto",
        "status_canceling": "Cancelando...",
        "profile_title": "Perfil de áudio",
        "profile_subtitle": "Escolha um vídeo de referência, extraia o perfil e aplique no processamento geral",
        "profile_no_file": "Sem arquivo",
        "btn_pick_video": "Escolher...",
        "btn_analyze": "Extrair perfil",
        "btn_clear_profile": "Apagar perfil",
        "group_output": "Saída",
        "waveform_group": "Waveform",
        "waveform_empty": "Selecione um video para ver a forma de onda.",
        "waveform_loading": "Gerando waveform...",
        "waveform_unavailable": "Nao foi possivel gerar a pre-visualizacao.",
        "btn_apply_profile": "Aplicar no processamento geral",
        "report_title": "Antes / depois",
        "report_file": "Arquivo",
        "report_before_i": "Antes (I)",
        "report_before_lra": "Antes (LRA)",
        "report_before_tp": "Antes (TP)",
        "report_after_i": "Depois (I)",
        "report_after_lra": "Depois (LRA)",
        "report_after_tp": "Depois (TP)",
        "btn_export_csv": "CSV",
        "btn_export_txt": "TXT",
        "btn_clear_report": "Limpar",
        "report_filename_base": "relatório",
        "group_summary": "Resumo",
        "summary_no_data": "Sem dados",
        "summary_text": "Total {total} · ok {ok} · erro {fail} · {ratio:.0f}%\nLUFS médio: {avg_before:.2f} -> {avg_after:.2f} (D {delta:+.2f})",
        "msg_attention": "Atenção",
        "msg_success": "Sucesso",
        "msg_error": "Erro",
        "msg_info": "Info",
        "msg_confirm": "Confirmar",
        "dialog_close": "Fechar",
        "settings_title": "Configuração",
        "settings_input": "Origem:",
        "settings_output": "Destino:",
        "settings_browse": "Explorar...",
        "settings_save": "Salvar",
        "settings_cancel": "Cancelar",
        "pick_input_folder": "Selecionar pasta de origem",
        "pick_output_folder": "Selecionar pasta de destino",
        "pick_reference_video": "Selecionar vídeo de referência",
        "video_filter": "Vídeos (*.mp4 *.mkv *.mov *.avi *.flv *.webm);;Todos (*.*)",
        "all_filter": "Todos (*.*)",
        "save_csv": "Salvar CSV",
        "save_txt": "Salvar TXT",
        "csv_filter": "CSV (*.csv);;Todos (*.*)",
        "txt_filter": "Texto (*.txt);;Todos (*.*)",
        "manual_title": "Manual",
        "manual_text": "Guia rapido:\n1. Selecione as pastas de Origem e Destino.\n2. Escolha um preset ou ajuste LUFS/LRA/TP manualmente.\n3. (Opcional) Use Perfil para extrair e aplicar uma referencia.\n4. Inicie o processamento e acompanhe o status por arquivo.\n5. Revise o Relatorio e exporte CSV/TXT.\n6. Se faltar FFmpeg, use Ajuda > Instalar FFmpeg.",
        "about_title": "Sobre",
        "about_text": "FFmpeg Master Vol Normalizer v{version}\n\nNormalizador de volume para vídeo/áudio com ffmpeg loudnorm.\nInterface: PyQt6\nLicença: MIT",
        "support_title": "Apoiar o projeto",
        "support_heading": "💙 Apoie o projeto",
        "support_message": "Se esta ferramenta foi útil para você e ajudou no seu trabalho, considere uma contribuição voluntária para apoiar a evolução e a manutenção do projeto.",
        "support_note": "✨ Sua ajuda contribui para melhorias, correções e novos recursos.",
        "support_target": "🔗 Transferência via PIX (chave): {target}",
        "support_scan_hint": "📱 Escaneie o QR Code ou copie a chave PIX abaixo.",
        "support_open": "Copiar chave PIX",
        "support_qr_error": "Não foi possível gerar o código QR agora.",
        "support_pix_copied": "Chave PIX copiada para a área de transferência.",
        "deps_missing_title": "Dependências ausentes",
        "deps_missing_text": "Dependencias obrigatorias ausentes:\n\n{missing}\n\nInstalar FFmpeg automaticamente com winget em um console?",
        "deps_installing_console": "Uma janela de console sera aberta para instalar o FFmpeg com winget. Aguarde o termino e volte ao aplicativo.",
        "deps_install_ok": "FFmpeg instalado com sucesso. O aplicativo vai continuar.",
        "ffmpeg_already_installed": "FFmpeg ja esta instalado no sistema. Nao e necessario instalar novamente.",
        "deps_install_fail": "Nao foi possivel instalar o FFmpeg automaticamente.\n\nDetalhe: {error}",
        "deps_install_fail_unknown": "Erro desconhecido durante a instalacao.",
        "cannot_start_without_ffmpeg": "Não é possível iniciar sem FFmpeg instalado.",
        "exit_title": "Sair",
        "exit_text": "Deseja sair?",
        "busy_title": "Aviso",
        "busy_text": "O aplicativo está processando. Cancele ou aguarde finalizar.",
        "language_spanish": "Espanhol",
        "language_english": "Inglês",
        "language_portuguese": "Português",
        "logs_title": "Logs",
        "logs_empty": "Ainda não há registros.",
        "error_reading_logs": "Erro ao ler logs: {error}",
        "errors_report_title": "Relatório de Erros",
        "errors_report_ok": "Nenhum erro encontrado.",
        "errors_report_header": "RELATÓRIO DE ERROS\n{line}\nTotal: {count}\n\n{items}",
        "update_deps_question": "Atualizar PyQt6 via pip?",
        "update_deps_ok": "Dependências atualizadas. Reinicie o aplicativo.",
        "update_deps_fail": "Não foi possível atualizar dependências.\n\n{error}",
        "deps_title": "Dependências",
        "deps_all_ok": "{info}\n\nTudo certo.",
        "deps_missing": "{info}\n\nDependências ausentes.",
        "clean_cache_question": "Excluir arquivos temporários?",
        "clean_cache_result": "{count} arquivos excluídos.",
        "restore_config_question": "Restaurar configuração padrão?",
        "restore_config_done": "Configuração restaurada. Reinicie o aplicativo.",
        "settings_saved": "Configuração salva.",
        "download_ffmpeg_title": "Instalar FFmpeg",
        "download_ffmpeg_question": "Instalar FFmpeg automaticamente com winget em um console?",
        "version_title": "Versão",
        "version_text": "Versão atual: {version}\nVerificado: {checked}\n\nVocê está usando a versão mais recente.",        "update_available_title": "Atualização disponível",
        "update_available_message": "Versão {latest} disponível (você tem {current})\n\nBaixá-la?",
        "update_check_error": "Não foi possível verificar atualizações. Tente mais tarde.",
        "update_up_to_date": "Você já tem a versão mais recente ({version}).",
        "btn_download": "Baixar",
        "btn_ignore": "Ignorar",
        "preset_label": "Preset:",
        "preset_custom": "Custom",
        "preset_applied": "Preset {name} aplicado ({lufs} LUFS · LRA {lra} · TP {tp} dB)",
        "gpu_label": "GPU accel:",
        "gpu_detected": "{method} detectado",
        "gpu_none": "Não disponível",
        "gpu_enabled_hint": "Acelera a leitura de vídeo com hardware",
        "parallel_label": "Paralelo:",
        "parallel_hint": "{workers} processos simultâneos",
        "processing_parallel": "Processando em paralelo ({workers}): {done}/{total}",
        "item_pending": "Pendente",
        "processing_item": "Processando {index}/{total}: {name}...",
        "status_analyzing": "Analisando...",
        "status_normalizing": "Normalizando...",
        "status_completed": "Concluído",
        "status_timeout": "Timeout",
        "status_canceled": "Cancelado",
        "status_error": "Erro",
        "status_success": "Sucesso",
        "status_finished": "Finalizado",
        "finished_counts": "Processados: {ok}\nErros: {fail}",
        "profile_analyzing": "Analisando...",
        "analyzer_saved": "Vídeo analisado. Perfil salvo.",
        "analysis_error_title": "Erro de análise",
        "no_videos_selected": "Selecione pelo menos um vídeo para normalizar.",
        "profile_applied": "Perfil de áudio aplicado com sucesso.\n\nLUFS: {lufs} · LRA: {lra} · TP: {tp} dB",
        "profile_info_loaded": "VÍDEO ANALISADO\n{line}\nArquivo: {filename}\nData: {date}\n\nPARÂMETROS DETECTADOS\n{line}\nInput Loudness (I): {input_i:.2f} LUFS\nLoudness Range (LRA): {input_lra:.2f} LU\nTrue Peak (TP): {input_tp:.2f} dB\nThreshold: {input_thresh:.2f} dB\nTarget Offset: {target_offset:.2f}\n\nPronto para usar como referência",
        "profile_info_empty": "SEM PERFIL CARREGADO\n\n1. Selecione um vídeo\n2. Clique em Extrair perfil\n3. Aguarde o resultado\n4. Aplique o perfil no processamento geral",
        "manual_text_full": "🎛️ NORMALIZADOR DE ÁUDIO · MANUAL PROFISSIONAL\n============================================================\n\n📌 1) Objetivo do aplicativo\nO Normalizador de Áudio padroniza o volume em lotes de vídeo para entregar\nreprodução consistente e profissional com FFmpeg + loudnorm (LUFS).\n\n✅ Indicado para:\n• Conteúdo web (YouTube, redes sociais, cursos)\n• Entregas corporativas\n• Bibliotecas grandes com volume irregular\n\n🧩 2) Visão geral da interface\nO app está dividido em 3 abas:\n\n1. 🎚️ Normalizar\n• Seleção de pasta de origem e destino\n• Lista de vídeos com status por arquivo\n• Presets rápidos: YouTube, Netflix, Spotify, Podcast, Custom\n• Ajuste manual de LUFS / LRA / TP\n• Aceleração por GPU opcional (quando disponível)\n• Controle de processamento paralelo\n\n2. 🧪 Perfil\n• Seleção de vídeo de referência\n• Extração automática de perfil de áudio\n• Pré-visualização de waveform\n• Aplicação do perfil no processamento geral\n\n3. 📊 Relatório\n• Métricas antes/depois: I, LRA, TP\n• Status por arquivo (sucesso, erro, cancelado, timeout)\n• Exportação em CSV e TXT\n• Resumo global com taxa de sucesso\n\n🚀 3) Fluxo recomendado\n1. Na aba Normalizar, clique em Origem e escolha a pasta de entrada.\n2. Clique em Destino e selecione uma pasta diferente para saída.\n3. Selecione os vídeos (arrastar e soltar, duplo clique ou Espaço).\n4. Escolha um preset ou ajuste LUFS/LRA/TP manualmente.\n5. (Opcional) Ative GPU accel e ajuste o Paralelo.\n6. Clique em Iniciar e acompanhe o progresso por arquivo.\n7. Abra Relatório e exporte CSV/TXT quando necessário.\n\n🎯 4) Guia rápido de parâmetros\n• LUFS: loudness percebido geral.\n  Base comum para web: -14 LUFS.\n• LRA: faixa dinâmica.\n  Menor = mais uniforme; maior = mais natural.\n• TP (True Peak): limite máximo de pico para evitar clipping.\n  Referência recomendada: -1.5 dB.\n\n🧠 5) Fluxo com Perfil de referência\n1. Abra a aba Perfil.\n2. Clique em Escolher... e selecione um vídeo de boa referência sonora.\n3. Clique em Extrair perfil.\n4. Revise os valores detectados e a waveform.\n5. Clique em Aplicar no processamento geral.\n6. Volte para Normalizar e rode o lote completo.\n\n🛠️ 6) Menus e utilitários\n📂 Arquivo\n• Atualizar dependências (PyQt6)\n• Verificar dependências\n• Limpar cache\n• Restaurar configuração\n\n🧰 Ferramentas\n• Ver logs\n• Relatório de erros\n• Configuração\n• Alternar tema\n\n❓ Ajuda\n• Manual\n• Apoiar o projeto\n• Instalar FFmpeg\n• Verificar atualizações\n\n🔐 7) Gestão automática de FFmpeg (novo)\nO aplicativo valida o FFmpeg na inicialização.\n\nSe o FFmpeg estiver ausente:\n• O app oferece instalação automática via winget em uma janela de console.\n• Após instalar, a disponibilidade é validada novamente.\n\nPelo menu Ajuda > Instalar FFmpeg:\n• Se o FFmpeg já estiver no sistema, o app informa que não é necessário\n  reinstalar.\n• Se estiver ausente, o fluxo automático é iniciado.\n\n⚠️ 8) Solução de problemas\n• FFmpeg não aparece após instalar: feche e abra o app novamente.\n• Lista vazia de vídeos: revise pasta de origem e formatos suportados.\n• Erro ao exportar: verifique permissão de escrita no destino.\n• Timeout em arquivos pesados: reduza o paralelo ou divida o lote.\n• Instabilidade de GPU: desative GPU accel e use CPU.\n\n💡 9) Boas práticas profissionais\n• Use sempre uma pasta de destino diferente da origem.\n• Faça teste com 1-2 arquivos antes de lotes grandes.\n• Use presets para agilidade e Custom para necessidades específicas.\n• Revise o relatório final para controle de qualidade e rastreabilidade.\n\n🏁 10) Resultado esperado\nVolume consistente, confortável e tecnicamente padronizado\nem todos os arquivos processados.",
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    table = TRANSLATIONS.get(lang, TRANSLATIONS["es"])
    value = table.get(key, TRANSLATIONS["es"].get(key, key))
    if kwargs:
        try:
            return value.format(**kwargs)
        except Exception:
            return value
    return value
